.PHONY: preview clean generate-index

DOCS := $(shell find . -name '*.md' -not -path './preview/*')
HTML := $(patsubst %.md,preview/%.html,$(DOCS))

preview: generate-index $(HTML) copy-assets
	@echo "✓ All HTML previews generated in preview/"
	@xdg-open "file://$(shell pwd)/preview/docs/index.html" 2>/dev/null || open "file://$(shell pwd)/preview/docs/index.html" 2>/dev/null || echo "Please open preview/docs/index.html manually"

generate-index:
	@echo "Generating docs/index.md..."
	@echo "# Documentation Index" > docs/index.md
	@echo "" >> docs/index.md
	@echo "**Generated:** $$(date '+%Y-%m-%d %H:%M:%S')" >> docs/index.md
	@echo "" >> docs/index.md
	@echo "## Recent Documents (by commit time)" >> docs/index.md
	@echo "" >> docs/index.md
	@for file in $$(git ls-files docs/*.md 2>/dev/null | grep -v 'docs/index.md' | while read f; do \
		COMMIT_TIME=$$(git log -1 --format=%ct "$$f" 2>/dev/null || echo 0); \
		echo "$$COMMIT_TIME $$f"; \
	done | sort -rn | cut -d' ' -f2-); do \
		BASENAME=$$(basename "$$file" .md); \
		TITLE=$$(grep -m1 '^# ' "$$file" 2>/dev/null | sed 's/^# //' || echo "$$BASENAME"); \
		COMMIT_DATE=$$(git log -1 --format=%ci "$$file" 2>/dev/null | cut -d' ' -f1 || echo "unknown"); \
		echo "- [$$TITLE]($$BASENAME.md) *($$COMMIT_DATE)*" >> docs/index.md; \
	done
	@echo "" >> docs/index.md
	@echo "---" >> docs/index.md
	@echo "*Auto-generated by \`make preview\`*" >> docs/index.md
	@echo "✓ Generated docs/index.md"

preview/%.html: %.md
	@mkdir -p $(dir $@)
	@sed 's/\.md)/\.html)/g' $< | pandoc -f markdown -o $@ --mathjax --standalone --metadata title="$(notdir $(basename $<))"
	@echo "✓ Generated $@"

.PHONY: copy-assets
copy-assets:
	@mkdir -p preview/reports
	@if [ -d reports ] && [ -n "$$(ls -A reports/*.svg 2>/dev/null)" ]; then \
		cp reports/*.svg preview/reports/ 2>/dev/null || true; \
		echo "✓ Copied SVG assets to preview/reports/"; \
	fi

clean:
	rm -rf preview/
	@echo "✓ Cleaned preview files"
