.PHONY: preview clean generate-index

DOCS := $(shell find . -name '*.md' -not -path './preview/*')
HTML := $(patsubst %.md,preview/%.html,$(DOCS))

preview: generate-index $(HTML) copy-assets
	@echo "✓ All HTML previews generated in preview/"
	@xdg-open "file://$(shell pwd)/preview/docs/index.html" 2>/dev/null || open "file://$(shell pwd)/preview/docs/index.html" 2>/dev/null || echo "Please open preview/docs/index.html manually"

generate-index:
	@echo "Generating docs/index.md..."
	@echo "# Documentation Index" > docs/index.md
	@echo "" >> docs/index.md
	@echo "**Generated:** $$(date '+%Y-%m-%d %H:%M:%S')" >> docs/index.md
	@echo "" >> docs/index.md
	@echo "## Theorems (Master References)" >> docs/index.md
	@echo "" >> docs/index.md
	@for file in docs/theorems/*/README.md; do \
		if [ -f "$$file" ]; then \
			TITLE=$$(grep -m1 '^# ' "$$file" 2>/dev/null | sed 's/^# //' || echo "$$(basename $$(dirname $$file))"); \
			RELPATH=$$(echo "$$file" | sed 's|^docs/||'); \
			echo "- [$$TITLE]($$RELPATH)" >> docs/index.md; \
		fi; \
	done
	@echo "" >> docs/index.md
	@echo "## Complete Proofs" >> docs/index.md
	@echo "" >> docs/index.md
	@for file in docs/proofs/*.md; do \
		if [ -f "$$file" ]; then \
			TITLE=$$(grep -m1 '^# ' "$$file" 2>/dev/null | sed 's/^# //' || echo "$$(basename $$file .md)"); \
			RELPATH=$$(echo "$$file" | sed 's|^docs/||'); \
			echo "- [$$TITLE]($$RELPATH)" >> docs/index.md; \
		fi; \
	done
	@echo "" >> docs/index.md
	@echo "## Recent Sessions (Last 10)" >> docs/index.md
	@echo "" >> docs/index.md
	@for file in $$(find docs/sessions -name '*.md' -type f | while read f; do \
		if git ls-files --error-unmatch "$$f" >/dev/null 2>&1; then \
			COMMIT_TIME=$$(git log -1 --format=%ct "$$f" 2>/dev/null || echo 0); \
		else \
			COMMIT_TIME=$$(stat -c %Y "$$f" 2>/dev/null || stat -f %m "$$f" 2>/dev/null || echo 0); \
		fi; \
		echo "$$COMMIT_TIME $$f"; \
	done | sort -rn | head -10 | cut -d' ' -f2-); do \
		TITLE=$$(grep -m1 '^# ' "$$file" 2>/dev/null | sed 's/^# //' || echo "$$(basename $$file .md)"); \
		COMMIT_DATE=$$(git log -1 --format=%ci "$$file" 2>/dev/null | cut -d' ' -f1 || echo "unknown"); \
		RELPATH=$$(echo "$$file" | sed 's|^docs/||'); \
		echo "- [$$TITLE]($$RELPATH) *($$COMMIT_DATE)*" >> docs/index.md; \
	done
	@echo "" >> docs/index.md
	@echo "## Navigation" >> docs/index.md
	@echo "" >> docs/index.md
	@echo "- [STATUS.md](STATUS.md) - Master status tracker" >> docs/index.md
	@echo "- [theorems/](theorems/) - All theorems organized by topic" >> docs/index.md
	@echo "- [proofs/](proofs/) - Complete standalone proofs" >> docs/index.md
	@echo "- [papers/](papers/) - LaTeX papers for publication" >> docs/index.md
	@echo "- [sessions/](sessions/) - Discovery narratives by date" >> docs/index.md
	@echo "- [failed-attempts/](failed-attempts/) - Dead ends (educational)" >> docs/index.md
	@echo "" >> docs/index.md
	@echo "---" >> docs/index.md
	@echo "*Auto-generated by \`make preview\`*" >> docs/index.md
	@echo "✓ Generated docs/index.md"

preview/%.html: %.md
	@mkdir -p $(dir $@)
	@sed 's/\.md)/\.html)/g' $< | pandoc -f markdown -o $@ --mathjax --standalone --metadata title="$(notdir $(basename $<))"
	@echo "✓ Generated $@"

.PHONY: copy-assets
copy-assets:
	@mkdir -p preview/reports
	@if [ -d reports ] && [ -n "$$(ls -A reports/*.svg 2>/dev/null)" ]; then \
		cp reports/*.svg preview/reports/ 2>/dev/null || true; \
		echo "✓ Copied SVG assets to preview/reports/"; \
	fi

clean:
	rm -rf preview/
	@echo "✓ Cleaned preview files"
