(* ::Package:: *)

(* Chebyshev Disk Approximation *)
(* The curve (t, ChebyshevPolygonFunction[t, k]) lies inside the unit disk *)
(* and touches the circle at k points. This module finds the closest point *)
(* on these curves to a given target in the disk. *)
(*                                                                         *)
(* Uses ChebyshevPolygonFunction from ChebyshevIntegralTheorem.wl:        *)
(*   f_k(t) = T_{k+1}(t) - t T_k(t) = -(1-t^2) U_{k-1}(t)             *)
(*   For t = cos(theta): f_k = -sin(k*theta)*sin(theta)                  *)
(*                                                                         *)
(* All computations use exact rational arithmetic when inputs are rational. *)
(* No N[] calls anywhere — polynomial Newton preserves rationality.        *)

BeginPackage["Orbit`"];

ChebyshevDiskApprox::usage = "ChebyshevDiskApprox[{x0, y0}, {kMin, kMax}] finds the point \
on the Chebyshev curves closest to target (x0, y0) in the unit disk.

ChebyshevDiskApprox[{x0, y0}, k] searches only curve k.

The algorithm screens a rational grid covering all lobes of each curve k, \
then Newton-refines from the best starting point. This ensures the global \
nearest point is found even when the target is far from x0's lobe.

All computations use exact rational arithmetic when inputs are rational. \
Newton minimizes D^2(t) = (t-x0)^2 + (f_k(t)-y0)^2 using Chebyshev \
derivative identities. No symbolic polynomial expansion needed.

Returns an Association with keys:
  \"t\"      - optimal parameter value (exact rational when inputs rational)
  \"k\"      - optimal curve index
  \"Point\"  - the point {t, f_k(t)} on the curve
  \"Target\" - the input {x0, y0}
  \"Error\"  - distance to target (Sqrt of rational)
  \"XError\" - |t - x0|
  \"YError\" - |f_k(t) - y0|

Example:
  ChebyshevDiskApprox[{1/3, 1/4}, {1, 50}]
  ChebyshevDiskApprox[{1/3, 1/4}, 10]";

ChebyshevDiskApprox::outofrange = "Target `1` is outside the closed unit disk.";

ChebyshevDiskPoint::usage = "ChebyshevDiskPoint[m, q, t] returns the point {x, y} on \
the rotated Chebyshev polygon curve, using the trig-free Weierstrass half-angle formula.

Parameters:
  m  - polygon order (positive integer)
  q  - rotation parameter (rational number, angle = 2 ArcTan[q])
  t  - curve parameter in [-1, 1]

Formula:
  c  = (1 - q^2)/(1 + q^2)
  sn = 2 q/(1 + q^2)
  u  = ChebyshevU[m - 1, t]
  {c t + sn (1 - t^2) u, sn t - c (1 - t^2) u}

Rational (m, q, t) -> rational (x, y). No trig functions.

Example:
  ChebyshevDiskPoint[2, 1/3, 1/3]";

ChebyshevDiskSample::usage = "ChebyshevDiskSample[n, maxDenom, kValues] generates n \
rational points in the unit disk using the rotated Chebyshev polygon parametrization.

Parameters:
  n         - number of points to generate
  maxDenom  - maximum denominator for rationalized random q and t
  kValues   - list of polygon orders (or single integer)

Each point is generated by drawing random q, t from Uniform[-1,1] (rationalized \
to the given maxDenom) and random m from kValues, then applying ChebyshevDiskPoint.

Returns a list of n points {{x1, y1}, {x2, y2}, ...}, all rational.

Example:
  ChebyshevDiskSample[100, 50, {2, 3, 5, 8, 13}]
  ChebyshevDiskSample[100, 50, 5]";

ChebyshevDiskUniformityTest::usage = "ChebyshevDiskUniformityTest[points] computes \
uniformity statistics for a set of 2D points in the unit disk.

Returns an Association with:
  \"RadialKS\"       - KS statistic for r^2 vs Uniform[0,1]
  \"AngularKS\"      - KS statistic for theta/(2 Pi) vs Uniform[0,1]
  \"ChiSquared\"     - chi-squared statistic (5 annuli x 8 sectors = 40 bins)
  \"ChiSquaredPValue\" - p-value from chi-squared distribution
  \"ClarkEvans\"     - Clark-Evans nearest-neighbor ratio (1.0 = uniform)
  \"MeanRadius\"     - mean radius (expected 2/3 for uniform disk)

All computations use numerical (N[]) values for speed.

Example:
  pts = RandomPoint[Disk[], 1000];
  ChebyshevDiskUniformityTest[pts]";

ChebyshevDiskUniformSample::usage = "ChebyshevDiskUniformSample[n, maxDenom] generates n \
uniformly distributed rational points in the unit disk via rejection sampling.

Draws x, y as RandomInteger[{-maxDenom, maxDenom}]/maxDenom (regular grid), \
accepts if x^2 + y^2 <= 1. Rejection rate is 1 - Pi/4 ~ 21.5%.

Returns a list of n rational points, uniformly distributed in the closed unit disk.

Example:
  ChebyshevDiskUniformSample[1000, 100]";

ChebyshevDiskRadialCorrect::usage = "ChebyshevDiskRadialCorrect[points] applies an \
empirical radial CDF correction to make r^2 uniformly distributed.

For each point, computes its rank among all r^2 values, then rescales the radius \
to Sqrt[rank/n] while preserving the angle. This exactly uniformizes the marginal \
radial distribution.

Note: this is a sample-specific correction (uses empirical CDF, not a parametric model). \
Angular correlations with radius, if present, are not corrected.

Returns a list of corrected points (numerical, not rational).

Example:
  pts = ChebyshevDiskSample[1000, 100, {2, 3, 5, 8, 13}];
  corrected = ChebyshevDiskRadialCorrect[pts];
  ChebyshevDiskUniformityTest[corrected]";

ChebyshevDiskHemisphereCorrect::usage = "ChebyshevDiskHemisphereCorrect[points] applies \
an analytical radial correction assuming the sample has the radial distribution of an \
orthographic hemisphere projection onto the disk.

For uniform points on the upper hemisphere projected to the disk, the CDF of r^2 is \
F(u) = 1 - Sqrt[1 - u]. The correction inverts this: new r^2 = 1 - Sqrt[1 - old r^2].

Unlike ChebyshevDiskRadialCorrect (empirical CDF), this is a closed-form pointwise \
map that can be applied to individual points without knowing the rest of the sample.

Preserves angles. Returns exact algebraic expressions (involving nested Sqrt).
Formula simplifies to: (x, y) / Sqrt[1 + Sqrt[1 - x^2 - y^2]].

Example:
  pts = ChebyshevDiskSample[1000, 100, {2, 3, 5, 8, 13}];
  corrected = ChebyshevDiskHemisphereCorrect[pts];
  ChebyshevDiskUniformityTest[corrected]";

ChebyshevDiskRationalCorrect::usage = "ChebyshevDiskRationalCorrect[points] applies an \
iterated rational radial correction that preserves rationality of the output.

Each iteration applies: (x, y) -> (x, y) * (1+d) / (1 + d*(x^2+y^2))
Default: d = -1/9, k = 3 iterations.

Near r=0 the net effect is r^2 -> r^2 * (1+d)^(2k), chosen so that \
(1+d)^(2k) ~ 1/2 to approximate the hemisphere projection CDF correction.

Properties:
  - Rational in -> rational out (no square roots)
  - Boundary preserved: r=1 maps to r=1
  - Origin preserved: r=0 maps to r=0
  - k iterations give a degree-2^k rational correction in r^2
  - For d in (-1, 0): compresses outward, expanding inner region

ChebyshevDiskRationalCorrect[points, d] uses a single iteration with parameter d.
ChebyshevDiskRationalCorrect[points, d, k] uses k iterations with parameter d.

Example:
  pts = ChebyshevDiskSample[1000, 100, {2, 3, 5, 8, 13}];
  corrected = ChebyshevDiskRationalCorrect[pts];
  ChebyshevDiskUniformityTest[corrected]
  (* All outputs remain exact rationals *)";

Begin["`Private`"];

(* ============================================================ *)
(* Evaluate f_k', f_k'' at a point using Chebyshev identities.  *)
(* No polynomial expansion — direct recurrence.                  *)
(*                                                               *)
(* f_k(t)  = ChebyshevPolygonFunction[t, k]                     *)
(* f_k'(t) = (k+1) U_k(t) - T_k(t) - k t U_{k-1}(t)          *)
(* f_k''(t) uses U_n'(t) = ((n+1)T_{n+1} - t U_n)/(t^2 - 1)  *)
(* ============================================================ *)

cdEvalFkDeriv[k_Integer, tn_] :=
  (k + 1) ChebyshevU[k, tn] - ChebyshevT[k, tn] - k tn ChebyshevU[k - 1, tn]

cdEvalFkDeriv2[k_Integer, tn_] :=
Module[{tSq1 = tn^2 - 1},
  ((k + 1) ((k + 1) ChebyshevT[k + 1, tn] - tn ChebyshevU[k, tn])
   - k tn (k ChebyshevT[k, tn] - tn ChebyshevU[k - 1, tn])) / tSq1
  - 2 k ChebyshevU[k - 1, tn]
]

(* ============================================================ *)
(* Newton step on D^2(t) = (t-x0)^2 + (f_k(t)-y0)^2           *)
(* Minimizes: solve dD^2/dt = 0 via Newton                     *)
(* Exact for rational inputs: all operations preserve Q         *)
(* ============================================================ *)

cdNewtonRefine[k_Integer, {x0_, y0_}, t0_, nSteps_Integer: 1] :=
Module[{tn = t0, fv, fpv, fppv, gn, gpn},
  Do[
    fv = ChebyshevPolygonFunction[tn, k];
    fpv = cdEvalFkDeriv[k, tn];
    fppv = cdEvalFkDeriv2[k, tn];
    (* g = dD^2/dt / 2 = (t - x0) + (f_k(t) - y0) f_k'(t) *)
    gn = (tn - x0) + (fv - y0) fpv;
    (* g' = 1 + f_k'(t)^2 + (f_k(t) - y0) f_k''(t) *)
    gpn = 1 + fpv^2 + (fv - y0) fppv;
    (* Bail out if at saddle/maximum of D^2 (g' <= 0) *)
    If[gpn <= 0, Break[]];
    tn = tn - gn/gpn,
    {nSteps}
  ];
  tn
]

(* ============================================================ *)
(* ChebyshevDiskApprox — main algorithm                        *)
(*                                                              *)
(* For each k, the curve f_k has k lobes (separated by zeros   *)
(* of U_{k-1}). A single Newton start from t=x0 can get stuck  *)
(* in the wrong lobe. Solution: screen a rational grid with     *)
(* ~3 points per lobe, Newton-refine from the best grid point. *)
(* ============================================================ *)

(* Single k convenience *)
ChebyshevDiskApprox[target : {_?NumericQ, _?NumericQ}, k_Integer?Positive] :=
  ChebyshevDiskApprox[target, {k, k}]

(* Main entry point *)
ChebyshevDiskApprox[{x0_?NumericQ, y0_?NumericQ},
                     {kMin_Integer?Positive, kMax_Integer?Positive}] :=
Module[{bestK = kMin, bestDistSq, fVal, yErrSq,
        tN, fN, distSq,
        gridResults, nTry, tStart,
        outT, outFVal, outXErr, outYErr},

  (* Validate target is in closed unit disk — exact for rationals *)
  If[x0^2 + y0^2 > 1,
    Message[ChebyshevDiskApprox::outofrange, {x0, y0}];
    Return[$Failed]
  ];

  (* Initialize with ExactX at kMin *)
  fVal = ChebyshevPolygonFunction[x0, kMin];
  bestDistSq = (fVal - y0)^2;
  outT = x0; outFVal = fVal; outXErr = 0; outYErr = Abs[fVal - y0];

  (* For each k: ExactX + grid screening + multi-start Newton *)
  Do[
    (* ExactX: evaluate f_k(x0) — zero x-error, measures y-error only *)
    fVal = ChebyshevPolygonFunction[x0, k];
    yErrSq = (fVal - y0)^2;
    If[yErrSq < bestDistSq,
      bestDistSq = yErrSq; bestK = k;
      outT = x0; outFVal = fVal; outXErr = 0; outYErr = Abs[fVal - y0]
    ];

    (* Grid screening: rational grid t_j = (j-k)/(k+1), j=0..2k *)
    (* Spacing 1/(k+1) gives ~3 points per lobe (width ~ pi/k)   *)
    (* Also include x0 as a candidate starting point               *)
    gridResults = Table[
      With[{tg = (j - k)/(k + 1)},
        {tg, (tg - x0)^2 + (ChebyshevPolygonFunction[tg, k] - y0)^2}],
      {j, 0, 2 k}
    ];
    AppendTo[gridResults, {x0, yErrSq}];
    gridResults = SortBy[gridResults, Last];

    (* Best grid point is a direct candidate (no Newton needed) *)
    If[gridResults[[1, 2]] < bestDistSq,
      With[{tBest = gridResults[[1, 1]]},
        fVal = ChebyshevPolygonFunction[tBest, k];
        bestDistSq = gridResults[[1, 2]]; bestK = k;
        outT = tBest; outFVal = fVal;
        outXErr = Abs[tBest - x0]; outYErr = Abs[fVal - y0]
      ]
    ];

    (* Newton-refine from top 3 grid points *)
    nTry = Min[3, Length[gridResults]];
    Do[
      tStart = gridResults[[i, 1]];
      tN = cdNewtonRefine[k, {x0, y0}, tStart];
      If[tN <= -1 || tN >= 1, Continue[]];
      fN = ChebyshevPolygonFunction[tN, k];
      distSq = (tN - x0)^2 + (fN - y0)^2;
      If[distSq < bestDistSq,
        bestDistSq = distSq; bestK = k;
        outT = tN; outFVal = fN;
        outXErr = Abs[tN - x0];
        outYErr = Abs[fN - y0]],
      {i, nTry}
    ],
    {k, kMin, kMax}
  ];

  <|
    "t" -> outT,
    "k" -> bestK,
    "Point" -> {outT, outFVal},
    "Target" -> {x0, y0},
    "Error" -> Sqrt[outXErr^2 + outYErr^2],
    "XError" -> outXErr,
    "YError" -> outYErr
  |>
]

(* ============================================================ *)
(* ChebyshevDiskPoint — trig-free rotated Chebyshev polygon    *)
(*                                                              *)
(* Uses Weierstrass half-angle substitution:                    *)
(*   cos(2 ArcTan[q]) = (1-q^2)/(1+q^2)                       *)
(*   sin(2 ArcTan[q]) = 2q/(1+q^2)                             *)
(* Rational (m, q, t) -> rational (x, y), no trig.             *)
(* ============================================================ *)

ChebyshevDiskPoint[m_Integer?Positive, q_, t_] :=
  With[{c = (1 - q^2)/(1 + q^2),
        sn = 2 q/(1 + q^2),
        u = ChebyshevU[m - 1, t]},
    {c t + sn (1 - t^2) u, sn t - c (1 - t^2) u}
  ]

(* ============================================================ *)
(* ChebyshevDiskSample — generate n rational disk points        *)
(*                                                              *)
(* Draws random q, t from Uniform[-1,1] rationalized to        *)
(* maxDenom, and m from kValues. Returns list of rational pts.  *)
(* ============================================================ *)

(* Single-k convenience *)
ChebyshevDiskSample[n_Integer?Positive, maxDenom_Integer?Positive, k_Integer?Positive] :=
  ChebyshevDiskSample[n, maxDenom, {k}]

ChebyshevDiskSample[n_Integer?Positive, maxDenom_Integer?Positive, kValues_List] :=
  Module[{qs, ts, ms},
    qs = Rationalize[RandomVariate[UniformDistribution[{-1, 1}], n], 1/maxDenom];
    ts = Rationalize[RandomVariate[UniformDistribution[{-1, 1}], n], 1/maxDenom];
    ms = RandomChoice[kValues, n];
    MapThread[ChebyshevDiskPoint, {ms, qs, ts}]
  ]

(* ============================================================ *)
(* ChebyshevDiskUniformSample — rejection sampling baseline     *)
(*                                                              *)
(* Draws (x, y) from [-1,1]^2, accepts if x^2 + y^2 <= 1.     *)
(* All outputs are rational. Rejection rate ~ 1 - Pi/4.        *)
(* ============================================================ *)

ChebyshevDiskUniformSample[n_Integer?Positive, maxDenom_Integer?Positive] :=
  Module[{pts = {}, batch, xs, ys, keep},
    While[Length[pts] < n,
      batch = Ceiling[1.3 (n - Length[pts])];
      xs = RandomInteger[{-maxDenom, maxDenom}, batch] / maxDenom;
      ys = RandomInteger[{-maxDenom, maxDenom}, batch] / maxDenom;
      keep = Pick[
        Transpose[{xs, ys}],
        MapThread[#1^2 + #2^2 <= 1 &, {xs, ys}]
      ];
      pts = Join[pts, keep]
    ];
    pts[[;; n]]
  ]

(* ============================================================ *)
(* ChebyshevDiskRadialCorrect — empirical CDF radial correction *)
(*                                                              *)
(* Ranks r^2 values, remaps radius to Sqrt[rank/n].            *)
(* Preserves angles, exactly uniformizes r^2 marginal.          *)
(* ============================================================ *)

ChebyshevDiskRadialCorrect[points_List] :=
  Module[{pts, n, radii, rSq, ordering, ranks, newRSq, scale},
    pts = N[points];
    n = Length[pts];
    radii = Sqrt[#[[1]]^2 + #[[2]]^2] & /@ pts;
    rSq = radii^2;

    (* Compute ranks: rank_i / n gives empirical CDF value *)
    ordering = Ordering[rSq];
    ranks = ConstantArray[0., n];
    Do[ranks[[ordering[[i]]]] = i, {i, n}];

    (* Target r^2 = (rank - 0.5) / n  (continuity correction) *)
    newRSq = (ranks - 0.5) / n;

    (* Scale factor: newR / oldR; handle r=0 *)
    scale = Table[
      If[radii[[i]] < 10^-15, 0., Sqrt[newRSq[[i]]] / radii[[i]]],
      {i, n}
    ];

    Table[pts[[i]] * scale[[i]], {i, n}]
  ]

(* ============================================================ *)
(* ChebyshevDiskHemisphereCorrect — analytical radial correction*)
(*                                                              *)
(* Hemisphere projection CDF: F(u) = 1 - Sqrt[1 - u]           *)
(* Correction: new r^2 = 1 - Sqrt[1 - old r^2]                 *)
(* Pointwise map, no sample statistics needed.                  *)
(* ============================================================ *)

ChebyshevDiskHemisphereCorrect[points_List] :=
  Map[
    With[{rSq = #[[1]]^2 + #[[2]]^2},
      If[rSq == 0, #,
        # / Sqrt[1 + Sqrt[1 - rSq]]
      ]
    ] &,
    points
  ]

(* ============================================================ *)
(* ChebyshevDiskRationalCorrect — rationality-preserving corr.  *)
(*                                                              *)
(* Mobius-type: (x,y) -> (x,y) * (1+d)/(1 + d*(x^2+y^2))      *)
(* Rational in -> rational out. Boundary and origin preserved.  *)
(* ============================================================ *)

ChebyshevDiskRationalCorrect[points_List] :=
  ChebyshevDiskRationalCorrect[points, -1/9, 3]

(* Single Mobius step with parameter d *)
ChebyshevDiskRationalCorrect[points_List, d_?NumericQ] :=
  ChebyshevDiskRationalCorrect[points, d, 1]

(* Iterated Mobius: same d applied k times *)
ChebyshevDiskRationalCorrect[points_List, d_?NumericQ, k_Integer?Positive] :=
  Module[{step},
    step[pts_] := Map[
      With[{rSq = #[[1]]^2 + #[[2]]^2},
        # (1 + d) / (1 + d rSq)
      ] &,
      pts
    ];
    Nest[step, points, k]
  ]

(* Sequential Mobius: different d at each step *)
ChebyshevDiskRationalCorrect[points_List, dList_List] :=
  Fold[
    Function[{pts, dVal},
      Map[
        With[{rSq = #[[1]]^2 + #[[2]]^2},
          # (1 + dVal) / (1 + dVal rSq)
        ] &,
        pts
      ]
    ],
    points,
    dList
  ]

(* ============================================================ *)
(* ChebyshevDiskUniformityTest — uniformity statistics          *)
(*                                                              *)
(* Computes radial KS, angular KS, equal-area chi-squared,     *)
(* Clark-Evans nearest-neighbor ratio, and mean radius.         *)
(* All computations use N[] for speed.                          *)
(* ============================================================ *)

ChebyshevDiskUniformityTest[points_List] :=
  Module[{pts, n, radii, rSq, angles, sortedRSq, ksRadial,
          sortedAng, ksAngular, nAnnuli = 5, nSectors = 8, nBins,
          expected, counts, annIdx, secIdx, chiSq, chiPVal,
          nf, dists, meanNN, expectedNN, clarkEvans, meanR},

    pts = N[points];
    n = Length[pts];

    (* Radii and angles *)
    radii = Sqrt[#[[1]]^2 + #[[2]]^2] & /@ pts;
    rSq = radii^2;
    angles = MapThread[
      Mod[ArcTan[#1, #2], 2 Pi] &,
      {pts[[All, 1]], pts[[All, 2]]}
    ];

    (* === Radial KS: r^2 should be Uniform[0,1] for uniform disk === *)
    sortedRSq = Sort[rSq];
    ksRadial = Max @ Table[
      Max[Abs[i/n - sortedRSq[[i]]], Abs[(i - 1)/n - sortedRSq[[i]]]],
      {i, n}
    ];

    (* === Angular KS: theta/(2 Pi) should be Uniform[0,1] === *)
    sortedAng = Sort[angles / (2 Pi)];
    ksAngular = Max @ Table[
      Max[Abs[i/n - sortedAng[[i]]], Abs[(i - 1)/n - sortedAng[[i]]]],
      {i, n}
    ];

    (* === Equal-area chi-squared: 5 annuli x 8 sectors = 40 bins === *)
    (* Annuli at r^2 = k/5 (equal area) *)
    nBins = nAnnuli * nSectors;
    expected = n / nBins;
    counts = ConstantArray[0, nBins];
    Do[
      annIdx = Clip[Ceiling[rSq[[i]] * nAnnuli], {1, nAnnuli}];
      secIdx = Clip[Ceiling[angles[[i]] / (2 Pi) * nSectors], {1, nSectors}];
      counts[[(annIdx - 1) * nSectors + secIdx]] += 1,
      {i, n}
    ];
    chiSq = Total[(counts - expected)^2 / expected];
    chiPVal = N[1 - CDF[ChiSquareDistribution[nBins - 1], chiSq]];

    (* === Clark-Evans nearest-neighbor ratio === *)
    nf = Nearest[pts];
    dists = Table[EuclideanDistance[pts[[i]], nf[pts[[i]], 2][[2]]], {i, n}];
    meanNN = Mean[dists];
    expectedNN = 1 / (2 Sqrt[n / Pi]);  (* expected for uniform in unit disk *)
    clarkEvans = meanNN / expectedNN;

    (* === Mean radius === *)
    meanR = Mean[radii];

    <|
      "RadialKS" -> ksRadial,
      "AngularKS" -> ksAngular,
      "ChiSquared" -> chiSq,
      "ChiSquaredPValue" -> chiPVal,
      "ClarkEvans" -> clarkEvans,
      "MeanRadius" -> meanR
    |>
  ]

End[];
EndPackage[];
